server:
  port: 11311
  servlet:
    jsp:
      init-parameters:
        development: true
  
spring:
  elasticsearch:
#    cluster-name: MyElastic
#    host: 127.0.0.1
    port : 9300
    cluster-name: Elog_application
    host: 175.115.95.93
    host2: 172.21.25.77
    
    
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://175.115.95.22:3306/project1
    username: websvc1
    password: websvc1
        

my:
  properties: 
     index: elog_index_2018.09.13
     type: elog_doctype

check:
  ip:
    official: 
       - 172.21.25.230
       - 172.21.25.200
       - 172.21.25.23
       - 172.21.25.198
       - 172.21.25.199
    external:
       - 172.21.25.206
       - 172.21.25.173
       - 172.21.25.172
    unauth:
       - 172.21.25.179
       - 172.21.25.79
       - 172.21.25.121
       - 172.21.25.225

